### ISSUE TITLE
Updog command not found

### ISSUE THREAD

**Issue by the4ndy** [sc0tfree/updog#12]
In a fresh Ubuntu env i installed pip3, then pip3 install updog (which succeeded without errors) and then when i try and run "updog" i get command not found :(

**Comment by the4ndy** [comment]
same thing happens with python3.7, pip3 (updated to latest) on a windows box as well (the term updog is not recognized as  the name of a commandlet......)

**Comment by ikarus23** [comment]
I guess there is something wrong with your python environment. Try using pythons virtual environments!
```
apt-get install python3-venv
python3 -m venv updog
source updog/bin/activate
pip install updog
updog
```
If you close the terminal or type `deactivate` the virtual python environment will be gone. If you want to use updog again, just use
```
source updog/bin/activate
updog
```
If you want to get rid of it, just delete the updog folder (python environment). No other dependencies somewhere in the system.

**Comment by sc0tfree** [comment]
Thanks, @ikarus23
