### ISSUE TITLE
Steps to generate SSL Certificates

### ISSUE THREAD

**Issue by umanghome** [sc0tfree/updog#13]
I get a `NET::ERR_CERT_AUTHORITY_INVALID` on Chrome. 
![image](https://user-images.githubusercontent.com/5698706/75103278-93fc1400-561e-11ea-842a-e5f883d3c803.png)

Command used: `updog -d . -p 8000 --ssl`

Do I need to generate the SSL certificate and set it somewhere manually? If so, can you give me the steps on how to do that so it'll work with updog? Or is it the same as how you would do it with `SimpleHTTPServer`? (I've never used SSL on `SimpleHTTPServer`)

**Comment by ikarus23** [comment]
What do you mean by
>Do I need to generate the SSL certificate and set it somewhere manually?

Updog will automatically provide a TLS certificate if you use `--ssl`. The warning in the browser just says that it has an unknown certificate authority. This is expected as you can not simply get a trusted certificate for "localhost".

Maybe it would be nice to get an option to provide your own certificate/key. But then again, this tool is most likely made for "quick and dirty", like SimpleHttpServer. If you want to host a real upload/download site, you probably better stick to real web servers like nginx/Apache/etc..

**Comment by sc0tfree** [comment]
Agreed with @ikarus23
