### ISSUE TITLE
Feature Request: CLI File Upload (Wget & Curl)

### ISSUE THREAD

**Issue by PowerPress** [sc0tfree/updog#29]
Here is an awesome feature request that would add massive pentest value.

I would like to be able to to use use curl and wget to upload files from linux boxes to my updog web server. This is great for when you have shell but no browser access and want an easy way to transfer files. Curl and Wget both these methods just need updog to support receiving them.

**Comment by dostoevskylabs** [comment]
Would something like this work for you?

```bash
curl -v -XPOST -F "file=@/etc/passwd;filename=passwd" -F "path=/path/to/store/file/on/updog" http://127.0.0.1:9090/upload
```

**Comment by KFDCompiled** [comment]
I'm sure I'm doing something wrong, but has this feature been implemented?

**Comment by KFDCompiled** [comment]
Yeah, I was doing something wrong.
